export const SERVICES = [
  {
    id: 1,
    title: "Crie uma Aplicação React Profissional para o seu Negócio",
    seller: "Alex Johnson",
    sellerAvatar: "https://i.pravatar.cc/64?img=11",
    sellerBio: "Desenvolvedor full-stack apaixonado por criar soluções escaláveis e modernas para empresas de todos os tamanhos.",
    sellerSince: "Mar 2020",
    sellerResponseTime: "2 horas",
    sellerLastDelivery: "Há cerca de 1 hora",
    sellerLocation: "São Paulo, Brasil",
    badge: null,
    badgeColor: "",
    rating: 4.9,
    reviews: 1240,
    ordersInQueue: 3,
    price: 250,
    category: "dev",
    categoryLabel: "Desenvolvimento & TI",
    available: true,
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80",
    thumbnails: [
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=200&q=80",
      "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=200&q=80",
    ],
    description:
      "Transformamos suas ideias em aplicações web modernas e performáticas com React. Como especialistas em desenvolvimento front-end, focamos em criar interfaces intuitivas e de alta qualidade que encantam os usuários.\n\nO que você receberá:",
    features: [
      "Aplicação React completa e responsiva",
      "Código limpo e bem documentado",
      "Integração com APIs REST",
      "Testes unitários incluídos",
      "Deploy configurado (Vercel/Netlify)",
    ],
    closing:
      "Trabalhamos com as melhores práticas do mercado e garantimos que a sua aplicação seja escalável e de fácil manutenção.",
    packages: {
      standard: { label: "App Básico", price: 250, delivery: 7, revisions: 2, features: ["Até 5 páginas", "Design responsivo", "Código fonte"] },
      premium: { label: "App Completo", price: 500, delivery: 14, revisions: 5, features: ["Páginas ilimitadas", "Design responsivo", "Código fonte", "Integração com API", "Deploy incluído"] },
    },
    testimonials: [
      { name: "Pedro Costa", initials: "PC", rating: 5, time: "Há 2 semanas", text: "Entrega impecável! O código é limpo e o projeto foi entregue antes do prazo. Recomendo muito." },
      { name: "Luisa Ferreira", initials: "LF", rating: 5, time: "Há 1 mês", text: "Excelente comunicação e resultado final surpreendente. Com certeza voltarei a contratar." },
    ],
  },
  {
    id: 2,
    title: "Scripts Python Personalizados para Processamento de Dados",
    seller: "Sarah Dev",
    sellerAvatar: "https://i.pravatar.cc/64?img=32",
    sellerBio: "Especialista em ciência de dados e automação com Python, com mais de 6 anos de experiência no mercado.",
    sellerSince: "Jun 2019",
    sellerResponseTime: "30 minutos",
    sellerLastDelivery: "Há cerca de 5 horas",
    sellerLocation: "Rio de Janeiro, Brasil",
    badge: "Mais Avaliado",
    badgeColor: "bg-green-100 text-green-700",
    rating: 5.0,
    reviews: 482,
    ordersInQueue: 1,
    price: 85,
    category: "dev",
    categoryLabel: "Desenvolvimento & TI",
    available: true,
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80",
    thumbnails: [
      "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=200&q=80",
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=200&q=80",
    ],
    description:
      "Criamos scripts Python sob medida para automatizar processos, processar grandes volumes de dados e gerar relatórios inteligentes para o seu negócio.\n\nO que você receberá:",
    features: [
      "Script Python otimizado e comentado",
      "Processamento de CSV, Excel ou JSON",
      "Relatórios automáticos em PDF/Excel",
      "Documentação de uso incluída",
    ],
    closing: "Entregamos soluções testadas, prontas para produção e com suporte pós-entrega.",
    packages: {
      standard: { label: "Script Básico", price: 85, delivery: 3, revisions: 2, features: ["1 script", "Até 1.000 linhas de dados", "Código fonte"] },
      premium: { label: "Automação Completa", price: 200, delivery: 7, revisions: 4, features: ["Scripts ilimitados", "Dados ilimitados", "Agendamento automático", "Suporte 30 dias"] },
    },
    testimonials: [
      { name: "Marcos Lima", initials: "ML", rating: 5, time: "Há 3 dias", text: "Script entregue com perfeição. Economizou horas de trabalho manual toda semana." },
      { name: "Carla Souza", initials: "CS", rating: 5, time: "Há 2 semanas", text: "Atendimento rápido e solução muito bem implementada. Nota 10!" },
    ],
  },
  {
    id: 3,
    title: "Configuração Completa de Loja Shopify e Customização de Tema",
    seller: "DigitalProv",
    sellerAvatar: "https://i.pravatar.cc/64?img=53",
    sellerBio: "Agência especializada em e-commerce Shopify com mais de 200 lojas lançadas no Brasil e exterior.",
    sellerSince: "Fev 2018",
    sellerResponseTime: "1 hora",
    sellerLastDelivery: "Há cerca de 2 horas",
    sellerLocation: "Curitiba, Brasil",
    badge: "Agência",
    badgeColor: "bg-purple-100 text-purple-700",
    rating: 4.8,
    reviews: 96,
    ordersInQueue: 5,
    price: 1200,
    category: "dev",
    categoryLabel: "Desenvolvimento & TI",
    available: false,
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
    thumbnails: [
      "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=200&q=80",
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=200&q=80",
    ],
    description:
      "Configuramos e personalizamos sua loja Shopify do zero até estar pronta para vender. Desde a escolha do tema até integrações avançadas de pagamento e logística.\n\nO que você receberá:",
    features: [
      "Configuração completa da loja",
      "Customização do tema escolhido",
      "Integração com meios de pagamento BR",
      "Configuração de frete e logística",
      "SEO básico configurado",
    ],
    closing: "Mais de 200 lojas entregues. Garantimos qualidade e suporte no pós-lançamento.",
    packages: {
      standard: { label: "Loja Básica", price: 1200, delivery: 10, revisions: 3, features: ["Até 50 produtos", "1 tema customizado", "Pagamentos configurados"] },
      premium: { label: "Loja Completa", price: 2500, delivery: 21, revisions: 5, features: ["Produtos ilimitados", "Tema customizado", "Integrações avançadas", "Treinamento incluído"] },
    },
    testimonials: [
      { name: "Fernanda Torres", initials: "FT", rating: 5, time: "Há 1 semana", text: "Loja entregue no prazo e com uma qualidade incrível. Já tivemos vendas no primeiro dia!" },
      { name: "Bruno Alves", initials: "BA", rating: 4, time: "Há 3 semanas", text: "Ótimo trabalho. Pequenos ajustes foram necessários mas foram resolvidos rapidamente." },
    ],
  },
  {
    id: 4,
    title: "Design de UI/UX para Aplicativo Móvel de Alta Fidelidade com Figma",
    seller: "UI/UX Studio",
    sellerAvatar: "https://i.pravatar.cc/64?img=24",
    sellerBio: "Designers apaixonados criando soluções centradas no usuário.",
    sellerSince: "Jan 2021",
    sellerResponseTime: "1 hora",
    sellerLastDelivery: "Há cerca de 3 horas",
    sellerLocation: "São Paulo, Brasil",
    badge: "Vendedor Pro",
    badgeColor: "bg-indigo-100 text-indigo-700",
    rating: 4.7,
    reviews: 210,
    ordersInQueue: 2,
    price: 450,
    category: "design",
    categoryLabel: "Design & Criativo",
    available: true,
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80",
    thumbnails: [
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=200&q=80",
      "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=200&q=80",
    ],
    description:
      "Transformamos suas ideias em experiências digitais impressionantes. Como especialistas em design de UI/UX, focamos em criar designs de aplicativos móveis intuitivos, modernos e de alta fidelidade que encantam os usuários e impulsionam o engajamento.\n\nO que você receberá:",
    features: [
      "Design de interface moderna e limpa (UI)",
      "Experiência do usuário otimizada (UX)",
      "Protótipo interativo no Figma",
      "Arquivos fonte totalmente editáveis",
      "Guia de estilo (Cores, Tipografia, Ícones)",
    ],
    closing:
      "Trabalhamos com as melhores práticas de mercado e garantimos que o seu aplicativo se destaque tanto no iOS quanto no Android.",
    packages: {
      standard: { label: "Design de App Pro", price: 450, delivery: 5, revisions: 3, features: ["Até 5 telas exclusivas", "Arquivo fonte (Figma)", "Protótipo funcional", "Design responsivo"] },
      premium: { label: "Design Completo", price: 950, delivery: 12, revisions: 5, features: ["Telas ilimitadas", "Arquivo fonte (Figma)", "Protótipo interativo avançado", "Design system completo", "Handoff para desenvolvedores"] },
    },
    testimonials: [
      { name: "Ricardo Mendes", initials: "RM", rating: 5, time: "Há 2 semanas", text: "Trabalho excepcional! O Studio entendeu perfeitamente o conceito do meu app e entregou telas que superaram as expectativas. Recomendo fortemente." },
      { name: "Ana Silva", initials: "AS", rating: 4, time: "Há 1 mês", text: "Comunicação fluida e entrega dentro do prazo. Os protótipos ajudaram muito na validação com os investidores." },
    ],
  },
  {
    id: 5,
    title: "Avaliação de Vulnerabilidade e Auditoria de Segurança para Aplicações Web",
    seller: "Shield Tech",
    sellerAvatar: "https://i.pravatar.cc/64?img=67",
    sellerBio: "Especialistas em cibersegurança com certificações internacionais e mais de 300 auditorias realizadas.",
    sellerSince: "Set 2020",
    sellerResponseTime: "2 horas",
    sellerLastDelivery: "Há cerca de 1 dia",
    sellerLocation: "Florianópolis, Brasil",
    badge: null,
    badgeColor: "",
    rating: 4.8,
    reviews: 55,
    ordersInQueue: 1,
    price: 300,
    category: "dev",
    categoryLabel: "Desenvolvimento & TI",
    available: true,
    image: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=800&q=80",
    thumbnails: [
      "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=200&q=80",
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=200&q=80",
    ],
    description:
      "Realizamos análises completas de segurança em aplicações web para identificar e corrigir vulnerabilidades antes que sejam exploradas por agentes maliciosos.\n\nO que você receberá:",
    features: [
      "Relatório completo de vulnerabilidades",
      "Testes OWASP Top 10",
      "Análise de código estático",
      "Recomendações de correção detalhadas",
      "Certificado de auditoria",
    ],
    closing: "Protegemos seu negócio com análises precisas e relatórios acionáveis.",
    packages: {
      standard: { label: "Auditoria Básica", price: 300, delivery: 5, revisions: 1, features: ["OWASP Top 10", "Relatório executivo", "1 revisão pós-correção"] },
      premium: { label: "Auditoria Completa", price: 750, delivery: 10, revisions: 3, features: ["OWASP Top 10 + extras", "Relatório técnico detalhado", "3 revisões", "Suporte 60 dias"] },
    },
    testimonials: [
      { name: "Tiago Nunes", initials: "TN", rating: 5, time: "Há 1 semana", text: "Encontraram vulnerabilidades críticas que passaram despercebidas. Relatório claro e objetivo." },
      { name: "Juliana Ramos", initials: "JR", rating: 5, time: "Há 2 meses", text: "Profissionalismo exemplar. Valeu cada centavo investido na segurança da nossa plataforma." },
    ],
  },
  {
    id: 6,
    title: "Criação de Conteúdo para Redes Sociais e Estratégia de Marketing Digital",
    seller: "MarketPro",
    sellerAvatar: "https://i.pravatar.cc/64?img=44",
    sellerBio: "Agência de marketing digital especializada em crescimento orgânico e criação de conteúdo estratégico.",
    sellerSince: "Nov 2019",
    sellerResponseTime: "45 minutos",
    sellerLastDelivery: "Há cerca de 6 horas",
    sellerLocation: "Belo Horizonte, Brasil",
    badge: "Mais Avaliado",
    badgeColor: "bg-green-100 text-green-700",
    rating: 4.9,
    reviews: 320,
    ordersInQueue: 4,
    price: 180,
    category: "marketing",
    categoryLabel: "Marketing Digital",
    available: true,
    image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80",
    thumbnails: [
      "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=200&q=80",
      "https://images.unsplash.com/photo-1432888622747-4eb9a8f5a307?w=200&q=80",
    ],
    description:
      "Criamos estratégias de conteúdo que engajam, convertem e fazem a sua marca crescer de forma orgânica nas principais redes sociais.\n\nO que você receberá:",
    features: [
      "Calendário editorial mensal",
      "30 posts prontos para publicar",
      "Artes personalizadas na identidade visual",
      "Legendas com copy persuasivo",
      "Relatório de desempenho",
    ],
    closing: "Conteúdo que converte. Estratégia que cresce. Marca que permanece.",
    packages: {
      standard: { label: "Pacote Essencial", price: 180, delivery: 7, revisions: 2, features: ["15 posts", "Artes básicas", "Calendário editorial"] },
      premium: { label: "Pacote Growth", price: 450, delivery: 10, revisions: 4, features: ["30 posts", "Artes premium", "Calendário editorial", "Stories + Reels", "Relatório mensal"] },
    },
    testimonials: [
      { name: "Giovana Melo", initials: "GM", rating: 5, time: "Há 4 dias", text: "Nosso engajamento triplicou no primeiro mês. Conteúdo criativo e estratégico como nunca tivemos antes." },
      { name: "Rafael Dias", initials: "RD", rating: 5, time: "Há 3 semanas", text: "Equipe super atenciosa e entregou muito além do esperado. Já renovamos para o próximo mês!" },
    ],
  },
];
